//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentId { get; set; }
        public string Text { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int Posts_PostId { get; set; }
        public int Users_UserId { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual User User { get; set; }
    }
}
